data:
  elasticsearch:
    host: 127.0.0.1
    port: 9200

management:
  endpoint:
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'

logging.level:
  root: ERROR
  org.springframework:
    boot.web.embedded.tomcat.TomcatWebServer: INFO
    web.client.RestTemplate: DEBUG
  fr.inra: DEBUG

faidare:
  elasticsearch-indexing-template:
    faidare_{documentType}_dev

  elasticsearch-xref-index-name:
    urgi_xref_dev

  cropOntology-repository-url:
    https://urgi.versailles.inra.fr/files/ephesis/trait-ontology/data_16.3/ontology-repository.json

  # Provides access to user group WS used to query private data ES aliases
  security-user-group-ws-url:
  security-user-group-ws-token:

  # TODO: Update URIs to match URL (update in generated JSON document too)
  # Warning! URIs should match with FAIDARE datadiscovery 'schema:includedInDataCatalog' field value
  data-sources:
  # URGI GnpIS
  - uri: https://urgi.versailles.inra.fr/gnpis
    url: https://urgi.versailles.inra.fr/gnpis
    name: URGI GnpIS
    image: https://urgi.versailles.inra.fr/files/faidare/logo/GnpIS.png
  # WUR EU-SOL BreeDB
  - uri: https://www.eu-sol.wur.nl/
    url: https://www.eu-sol.wur.nl/
    name: WUR EU-SOL BreeDB
    image: https://urgi.versailles.inra.fr/files/faidare/logo/EU-SOL.png
  # VIB PIPPA
  - uri: http://pippa.psb.ugent.be
    url: http://pippa.psb.ugent.be
    name: VIB PIPPA
    image: https://urgi.versailles.inra.fr/files/faidare/logo/VIB.png
  # IBET BioData
  - uri: https://biodata.pt
    url: https://biodata.pt
    name: IBET BioData
    image: https://urgi.versailles.inra.fr/files/faidare/logo/biodata.png
  # NIB PISA
  - uri: http://nib.si
    url: http://www.pisa.nib.si
    name: NIB PISA
    image: https://urgi.versailles.inra.fr/files/faidare/logo/NIB.png
  # CIRAD TropGENE
  - uri: http://tropgenedb.cirad.fr
    url: http://tropgenedb.cirad.fr
    name: CIRAD TropGENE
    image: https://urgi.versailles.inra.fr/files/faidare/logo/CIRAD.jpg
  # EVA
  - uri: https://www.ebi.ac.uk/eva
    url: https://www.ebi.ac.uk/eva
    name: EVA
    image: https://urgi.versailles.inra.fr/files/faidare/logo/EVA.png
  # ENA
  - uri: https://www.ebi.ac.uk/eva
    url: https://www.ebi.ac.uk/eva
    name: EBI European Nucleotide Archive
    image: https://urgi.versailles.inra.fr/files/faidare/logo/EVA.png
  # TERRA-REF
  - uri: https://terraref.org
    url: https://terraref.org
    name: TERRA-REF
    image: https://urgi.versailles.inra.fr/files/faidare/logo/TERRAREF.png
server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css
      - text/markdown
  port: 8380
  servlet:
    context-path: /faidare-dev

